# Generated by Django 5.0.1 on 2025-11-17 12:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(max_length=255, unique=True, verbose_name='Instagram ID')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='Подпись')),
                ('media_url', models.URLField(max_length=500, verbose_name='URL медиа')),
                ('media_type', models.CharField(max_length=50, verbose_name='Тип медиа')),
                ('permalink', models.URLField(max_length=500, verbose_name='Ссылка')),
                ('timestamp', models.DateTimeField(verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instagram пост',
                'verbose_name_plural': 'Instagram посты',
                'db_table': 'instagram_posts',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус')),
                ('ai_response', models.TextField(blank=True, null=True, verbose_name='Ответ AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Este Nómada', max_length=255, verbose_name='Название сайта')),
                ('site_description', models.TextField(blank=True, null=True, verbose_name='Описание сайта')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email для контактов')),
                ('telegram_channel', models.URLField(blank=True, null=True, verbose_name='Telegram канал')),
                ('bot_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram Bot Token')),
                ('channel_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram Channel ID')),
                ('auto_sync', models.BooleanField(default=False, verbose_name='Автосинхронизация')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('image', models.URLField(blank=True, max_length=500, null=True, verbose_name='Изображение')),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Порядок')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'db_table': 'menu_items',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['category'], name='menu_items_categor_b122d3_idx'), models.Index(fields=['active'], name='menu_items_active_b8ebf9_idx'), models.Index(fields=['order'], name='menu_items_order_da1006_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.menuitem', verbose_name='Блюдо')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='core.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Элемент заказа',
                'verbose_name_plural': 'Элементы заказа',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='URL')),
                ('date', models.DateField(verbose_name='Дата')),
                ('excerpt', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('cover_image', models.URLField(blank=True, max_length=500, null=True, verbose_name='Обложка')),
                ('source', models.CharField(choices=[('manual', 'Ручной'), ('telegram', 'Telegram')], default='manual', max_length=20, verbose_name='Источник')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
                'db_table': 'stories',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='stories_slug_19fa93_idx'), models.Index(fields=['date'], name='stories_date_6ae76c_idx'), models.Index(fields=['published'], name='stories_publish_1f73ac_idx')],
            },
        ),
    ]
