# Generated by Django 5.0.1 on 2025-11-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=10, verbose_name='Локаль')),
                ('namespace', models.CharField(max_length=100, verbose_name='Пространство имён')),
                ('key', models.CharField(max_length=255, verbose_name='Ключ')),
                ('value', models.TextField(verbose_name='Значение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Перевод',
                'verbose_name_plural': 'Переводы',
                'db_table': 'translations',
                'indexes': [models.Index(fields=['locale', 'namespace'], name='translation_locale_cd8089_idx')],
                'unique_together': {('locale', 'namespace', 'key')},
            },
        ),
    ]
