# Generated by Django 5.0.1 on 2025-11-17 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Категория (базовая)'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (базовое)'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название (базовое)'),
        ),
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(verbose_name='Содержание (базовое)'),
        ),
        migrations.AlterField(
            model_name='story',
            name='excerpt',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание (базовое)'),
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(max_length=500, unique=True, verbose_name='URL (базовый)'),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Заголовок (базовый)'),
        ),
        migrations.CreateModel(
            name='MenuItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=10, verbose_name='Локаль')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.menuitem', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Перевод блюда',
                'verbose_name_plural': 'Переводы блюд',
                'db_table': 'menu_item_translations',
                'indexes': [models.Index(fields=['menu_item', 'locale'], name='menu_item_t_menu_it_c4048a_idx')],
                'unique_together': {('menu_item', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='StoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=10, verbose_name='Локаль')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=500, verbose_name='URL')),
                ('excerpt', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.story', verbose_name='История')),
            ],
            options={
                'verbose_name': 'Перевод истории',
                'verbose_name_plural': 'Переводы историй',
                'db_table': 'story_translations',
                'indexes': [models.Index(fields=['story', 'locale'], name='story_trans_story_i_ad342a_idx'), models.Index(fields=['slug'], name='story_trans_slug_d2a69e_idx')],
                'unique_together': {('story', 'locale')},
            },
        ),
    ]
