# Generated by Django 5.0.1 on 2025-11-17 13:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_menuitem_category_alter_menuitem_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500, verbose_name='URL изображения')),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.menuitem', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Изображение блюда',
                'verbose_name_plural': 'Изображения блюд',
                'db_table': 'menu_item_images',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['menu_item', 'order'], name='menu_item_i_menu_it_0a690a_idx')],
            },
        ),
    ]
