# Generated by Django 5.0.1 on 2025-11-17 13:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_menuitemimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=10, verbose_name='Локаль')),
                ('name', models.CharField(max_length=255, verbose_name='Название атрибута')),
                ('value', models.CharField(max_length=500, verbose_name='Значение')),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='core.menuitem', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Атрибут блюда',
                'verbose_name_plural': 'Атрибуты блюд',
                'db_table': 'menu_item_attributes',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['menu_item', 'locale'], name='menu_item_a_menu_it_2a40e5_idx'), models.Index(fields=['menu_item', 'order'], name='menu_item_a_menu_it_b0630f_idx')],
            },
        ),
    ]
