# Generated by Django 5.0.1 on 2025-11-17 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_menuitemattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_interval', models.IntegerField(default=5000, help_text='Время в миллисекундах между переключениями слайдов', validators=[django.core.validators.MinValueValidator(1000)], verbose_name='Интервал переключения (мс)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки Hero',
                'verbose_name_plural': 'Настройки Hero',
                'db_table': 'hero_settings',
            },
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500, verbose_name='URL изображения')),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Порядок')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero изображение',
                'verbose_name_plural': 'Hero изображения',
                'db_table': 'hero_images',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['active', 'order'], name='hero_images_active_2d1257_idx')],
            },
        ),
    ]
