# Generated by Django 5.0.1 on 2025-11-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_herosettings_heroimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='menuitemimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL изображения'),
        ),
    ]
