# Generated by Django 5.0.1 on 2025-11-17 19:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_menuitemimage_image_alter_menuitemimage_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок (базовый)')),
                ('description', models.TextField(verbose_name='Описание (базовое)')),
                ('mission_text', models.TextField(blank=True, verbose_name='Текст миссии (базовый)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Изображение')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='URL изображения')),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Порядок')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Раздел "О нас"',
                'verbose_name_plural': 'Разделы "О нас"',
                'db_table': 'about_sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutSectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=10, verbose_name='Локаль')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('mission_text', models.TextField(blank=True, verbose_name='Текст миссии')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.aboutsection', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Перевод раздела "О нас"',
                'verbose_name_plural': 'Переводы разделов "О нас"',
                'db_table': 'about_section_translations',
                'unique_together': {('section', 'locale')},
            },
        ),
    ]
