# Generated by Django 5.0.1 on 2025-11-17 19:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def forward_migrate_data(apps, schema_editor):
    """Добавляем новые поля с дефолтными значениями для существующих записей."""
    db_alias = schema_editor.connection.alias
    
    # Используем Django ORM вместо сырого SQL для совместимости с SQLite и MySQL
    # На этом этапе модель ещё называется AboutSection
    AboutSection = apps.get_model('core', 'AboutSection')
    AboutSectionTranslation = apps.get_model('core', 'AboutSectionTranslation')
    
    # Обновляем все разделы
    for section in AboutSection.objects.all():
        section.section_id = f'about-{section.id}'
        section.section_type = 'about'
        section.subtitle = ''
        # Копируем mission_text в content
        if hasattr(section, 'mission_text'):
            section.content = section.mission_text
        section.save()
    
    # Обновляем все переводы
    for translation in AboutSectionTranslation.objects.all():
        translation.subtitle = ''
        # Копируем mission_text в content
        if hasattr(translation, 'mission_text'):
            translation.content = translation.mission_text
        translation.save()


def backward_migrate_data(apps, schema_editor):
    """При откате миграции восстанавливаем данные."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_aboutsection_aboutsectiontranslation'),
    ]

    operations = [
        # 1. Переименовываем таблицы
        migrations.AlterModelTable(
            name='aboutsection',
            table='content_sections',
        ),
        migrations.AlterModelTable(
            name='aboutsectiontranslation',
            table='content_section_translations',
        ),
        
        # 2. Добавляем новые поля
        migrations.AddField(
            model_name='aboutsection',
            name='section_type',
            field=models.CharField(
                choices=[('about', 'О нас'), ('hero', 'Главный экран'), ('services', 'Услуги'), 
                        ('features', 'Особенности'), ('testimonials', 'Отзывы'), ('team', 'Команда'), 
                        ('custom', 'Пользовательский')], 
                default='about', 
                max_length=50, 
                verbose_name='Тип раздела'
            ),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='section_id',
            field=models.CharField(max_length=100, null=True, verbose_name='ID раздела (для ссылок)'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, default='', verbose_name='Подзаголовок (базовый)'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Дополнительный контент (базовый)'),
        ),
        migrations.AddField(
            model_name='aboutsectiontranslation',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, default='', verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='aboutsectiontranslation',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Дополнительный контент'),
        ),
        
        # 3. Мигрируем данные
        migrations.RunPython(forward_migrate_data, backward_migrate_data),
        
        # 4. Делаем section_id уникальным и обязательным
        migrations.AlterField(
            model_name='aboutsection',
            name='section_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='ID раздела (для ссылок)'),
        ),
        
        # 5. Переименовываем модели
        migrations.RenameModel(
            old_name='AboutSection',
            new_name='ContentSection',
        ),
        migrations.RenameModel(
            old_name='AboutSectionTranslation',
            new_name='ContentSectionTranslation',
        ),
        
        # 6. Обновляем мета-данные
        migrations.AlterModelOptions(
            name='contentsection',
            options={
                'verbose_name': 'Раздел контента',
                'verbose_name_plural': 'Разделы контента',
                'ordering': ['section_type', 'order'],
            },
        ),
        migrations.AlterModelOptions(
            name='contentsectiontranslation',
            options={
                'verbose_name': 'Перевод раздела контента',
                'verbose_name_plural': 'Переводы разделов контента',
            },
        ),
        
        # 7. Добавляем индексы
        migrations.AddIndex(
            model_name='contentsection',
            index=models.Index(fields=['section_type', 'published'], name='content_sec_type_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='contentsection',
            index=models.Index(fields=['section_id'], name='content_sec_id_idx'),
        ),
        
        # 8. Переименовываем upload_to для изображений
        migrations.AlterField(
            model_name='contentsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sections/', verbose_name='Изображение'),
        ),
        
        # 9. Удаляем старое поле mission_text (оно теперь в content)
        migrations.RemoveField(
            model_name='contentsection',
            name='mission_text',
        ),
        migrations.RemoveField(
            model_name='contentsectiontranslation',
            name='mission_text',
        ),
    ]
