# Generated by Django 5.0.1 on 2025-11-18 10:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_about_to_content_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Поддерживает HTML', verbose_name='Содержимое')),
                ('position', models.CharField(choices=[('left', 'Слева'), ('center', 'По центру'), ('right', 'Справа')], default='left', max_length=10, verbose_name='Позиция в футере')),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Порядок')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Секция футера',
                'verbose_name_plural': 'Секции футера',
                'db_table': 'footer_sections',
                'ordering': ['position', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FooterSectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=10, verbose_name='Локаль')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержимое')),
            ],
            options={
                'verbose_name': 'Перевод секции футера',
                'verbose_name_plural': 'Переводы секций футера',
                'db_table': 'footer_section_translations',
            },
        ),
        migrations.RenameIndex(
            model_name='contentsection',
            new_name='content_sec_section_8d668b_idx',
            old_name='content_sec_type_pub_idx',
        ),
        migrations.RenameIndex(
            model_name='contentsection',
            new_name='content_sec_section_5bc928_idx',
            old_name='content_sec_id_idx',
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='content',
            field=models.TextField(blank=True, verbose_name='Дополнительный контент (базовый)'),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='section_type',
            field=models.CharField(choices=[('about', 'О нас'), ('hero', 'Главный экран'), ('services', 'Услуги'), ('features', 'Особенности'), ('testimonials', 'Отзывы'), ('team', 'Команда'), ('custom', 'Пользовательский')], default='custom', max_length=50, verbose_name='Тип раздела'),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок (базовый)'),
        ),
        migrations.AlterField(
            model_name='contentsectiontranslation',
            name='content',
            field=models.TextField(blank=True, verbose_name='Дополнительный контент'),
        ),
        migrations.AlterField(
            model_name='contentsectiontranslation',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок'),
        ),
        migrations.AddIndex(
            model_name='footersection',
            index=models.Index(fields=['position', 'order'], name='footer_sect_positio_bede67_idx'),
        ),
        migrations.AddIndex(
            model_name='footersection',
            index=models.Index(fields=['published'], name='footer_sect_publish_0433d8_idx'),
        ),
        migrations.AddField(
            model_name='footersectiontranslation',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.footersection', verbose_name='Секция'),
        ),
        migrations.AlterUniqueTogether(
            name='footersectiontranslation',
            unique_together={('section', 'locale')},
        ),
    ]
