# Generated by Django 5.0.1 on 2025-11-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_footersection_footersectiontranslation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersection',
            name='text_align',
            field=models.CharField(choices=[('left', 'По левому краю'), ('center', 'По центру'), ('right', 'По правому краю'), ('justify', 'По ширине')], default='left', max_length=10, verbose_name='Выравнивание текста'),
        ),
    ]
