# Generated by Django 5.0.1 on 2025-11-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_footersection_text_align'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Логотип сайта'),
        ),
    ]
