# Generated by Django 5.0.1 on 2025-11-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_logo_to_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Изображение (загрузка файла)'),
        ),
        migrations.AlterField(
            model_name='heroimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL изображения (альтернатива)'),
        ),
    ]
