# Generated by Django 5.0.1 on 2025-11-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_image_to_heroimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosettings',
            name='transition_effect',
            field=models.CharField(choices=[('crossfade', 'Плавное растворение (Crossfade)'), ('fade', 'Исчезновение и появление (Fade)'), ('slide', 'Слайд (Slide)')], default='crossfade', help_text='Эффект анимации при смене слайдов', max_length=20, verbose_name='Эффект перехода'),
        ),
    ]
