# Generated by Django 5.0.1 on 2025-11-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_transition_effect_to_hero_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='cover_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='stories/', verbose_name='Обложка (загрузка файла)'),
        ),
        migrations.AlterField(
            model_name='footersection',
            name='title',
            field=models.CharField(help_text='Поддерживает HTML', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='footersectiontranslation',
            name='content',
            field=models.TextField(help_text='Поддерживает HTML', verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='footersectiontranslation',
            name='title',
            field=models.CharField(help_text='Поддерживает HTML', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='story',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Обложка (URL)'),
        ),
    ]
