# Generated by Django 5.0.1 on 2025-11-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_cover_image_file_to_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='related_stories',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='core.story', verbose_name='Связанные истории'),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='content',
            field=models.TextField(blank=True, help_text='Поддерживает HTML', verbose_name='Дополнительный контент (базовый)'),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='description',
            field=models.TextField(help_text='Поддерживает HTML', verbose_name='Описание (базовое)'),
        ),
        migrations.AlterField(
            model_name='contentsectiontranslation',
            name='description',
            field=models.TextField(help_text='Поддерживает HTML', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, help_text='Поддерживает HTML', null=True, verbose_name='Описание (базовое)'),
        ),
        migrations.AlterField(
            model_name='menuitemtranslation',
            name='description',
            field=models.TextField(blank=True, help_text='Поддерживает HTML', null=True, verbose_name='Описание'),
        ),
    ]
