# Generated by Django 5.0.1 on 2025-11-25 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_related_stories_to_menu_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishTTK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttk_file', models.FileField(help_text='Загрузите файл технико-технологической карты в формате Markdown (.md)', upload_to='ttk/', verbose_name='Файл ТТК (.md)')),
                ('version', models.CharField(blank=True, help_text='Номер или название версии ТТК (например: 1.0, 2024-01)', max_length=50, null=True, verbose_name='Версия ТТК')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные заметки о ТТК', null=True, verbose_name='Примечания')),
                ('active', models.BooleanField(default=True, help_text='Активна ли данная версия ТТК', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('menu_item', models.OneToOneField(help_text='Выберите блюдо, для которого создается ТТК', on_delete=django.db.models.deletion.CASCADE, related_name='ttk', to='core.menuitem', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'ТТК блюда',
                'verbose_name_plural': 'ТТК блюд',
                'db_table': 'dish_ttk',
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['menu_item'], name='dish_ttk_menu_it_840192_idx'), models.Index(fields=['active'], name='dish_ttk_active_ddaec9_idx')],
            },
        ),
    ]
