# Generated by Django 5.0.1 on 2025-11-28 09:01

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_merge_0024_and_0025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключ сессии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'db_table': 'carts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_point_latitude', models.DecimalField(decimal_places=6, help_text='Широта вашей точки доставки (например, 43.3619 для Астурии)', max_digits=9, verbose_name='Широта точки доставки')),
                ('delivery_point_longitude', models.DecimalField(decimal_places=6, help_text='Долгота вашей точки доставки (например, -5.8494 для Астурии)', max_digits=9, verbose_name='Долгота точки доставки')),
                ('base_delivery_cost', models.DecimalField(decimal_places=2, default=0, help_text='Минимальная стоимость доставки', max_digits=10, verbose_name='Базовая стоимость доставки (€)')),
                ('cost_per_km', models.DecimalField(decimal_places=2, default=0, help_text='Дополнительная стоимость за каждый километр расстояния', max_digits=10, verbose_name='Стоимость за километр (€)')),
                ('free_delivery_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Если сумма заказа превышает это значение, доставка бесплатна', max_digits=10, null=True, verbose_name='Порог бесплатной доставки (€)')),
                ('max_delivery_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Максимальное расстояние, на которое возможна доставка', max_digits=10, null=True, verbose_name='Максимальное расстояние доставки (км)')),
                ('cart_enabled', models.BooleanField(default=True, verbose_name='Корзина включена')),
                ('favorites_enabled', models.BooleanField(default=True, verbose_name='Избранное включено')),
                ('registration_required', models.BooleanField(default=False, help_text='Если включено, пользователи должны регистрироваться для оформления заказа', verbose_name='Требуется регистрация для заказа')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройки доставки и ЛК',
                'verbose_name_plural': 'Настройки доставки и ЛК',
                'db_table': 'delivery_settings',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключ сессии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'db_table': 'favorites',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки (€)'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Расстояние доставки (км)'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=core.models.EncryptedField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=core.models.EncryptedField(blank=True, max_length=50, null=True, verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.cart', verbose_name='Корзина')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.menuitem', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Элемент корзины',
                'verbose_name_plural': 'Элементы корзины',
                'db_table': 'cart_items',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', core.models.EncryptedField(max_length=255, verbose_name='Email')),
                ('phone', core.models.EncryptedField(max_length=50, verbose_name='Телефон')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Почтовый индекс')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('is_registered', models.BooleanField(default=False, verbose_name='Зарегистрирован')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email подтвержден')),
                ('email_verification_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Токен подтверждения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='core.customer', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.customer', verbose_name='Клиент'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer'], name='orders_custome_6c3a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_status_762191_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_created_77e2b9_idx'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='core.customer', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.menuitem', verbose_name='Блюдо'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart'], name='cart_items_cart_id_3caa7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'menu_item')},
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='customers_email_92e882_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_registered'], name='customers_is_regi_6148b4_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email_verified'], name='customers_email_v_5cf81d_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['customer'], name='carts_custome_91bdb8_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_key'], name='carts_session_2c783d_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['customer'], name='favorites_custome_0046eb_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['session_key'], name='favorites_session_bdd716_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('customer', 'menu_item'), ('session_key', 'menu_item')},
        ),
    ]
