# Generated by Django 5.0.1 on 2025-11-28 11:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_cart_deliverysettings_favorite_order_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Порядок отображения')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория блюд',
                'verbose_name_plural': 'Категории блюд',
                'db_table': 'menu_item_categories',
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=10, verbose_name='Локаль')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Перевод категории блюд',
                'verbose_name_plural': 'Переводы категорий блюд',
                'db_table': 'menu_item_category_translations',
            },
        ),
        migrations.RemoveIndex(
            model_name='menuitem',
            name='menu_items_categor_b122d3_idx',
        ),
        migrations.RemoveField(
            model_name='menuitemtranslation',
            name='category',
        ),
        migrations.AddIndex(
            model_name='menuitemcategory',
            index=models.Index(fields=['order_id'], name='menu_item_c_order_i_54c505_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitemcategory',
            index=models.Index(fields=['active'], name='menu_item_c_active_c621fc_idx'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='core.menuitemcategory', verbose_name='Категория'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['category', 'active'], name='menu_items_categor_6f3835_idx'),
        ),
        migrations.AddField(
            model_name='menuitemcategorytranslation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.menuitemcategory', verbose_name='Категория'),
        ),
        migrations.AddIndex(
            model_name='menuitemcategorytranslation',
            index=models.Index(fields=['category', 'locale'], name='menu_item_c_categor_4a609a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitemcategorytranslation',
            unique_together={('category', 'locale')},
        ),
    ]
