# Generated by Django 5.0.1 on 2025-11-28 12:18

from django.db import migrations
from django.utils.text import slugify


def create_missing_translations(apps, schema_editor):
    """Создаем недостающие переводы на три языка (ru, es, en) для всех существующих записей."""
    db_alias = schema_editor.connection.alias
    
    # Локали для создания переводов
    locales = ['ru', 'es', 'en']
    
    # 1. MenuItemCategory и MenuItemCategoryTranslation
    MenuItemCategory = apps.get_model('core', 'MenuItemCategory')
    MenuItemCategoryTranslation = apps.get_model('core', 'MenuItemCategoryTranslation')
    
    for category in MenuItemCategory.objects.using(db_alias).all():
        for locale in locales:
            # Проверяем, существует ли уже перевод
            if not MenuItemCategoryTranslation.objects.using(db_alias).filter(
                category=category, locale=locale
            ).exists():
                # Получаем первый существующий перевод для копирования или используем базовое значение
                existing_translation = category.translations.first()
                if existing_translation:
                    name = existing_translation.name
                    description = existing_translation.description
                else:
                    # Используем базовое значение из модели (если есть)
                    name = f'Категория #{category.id}'
                    description = None
                
                # Создаем перевод
                MenuItemCategoryTranslation.objects.using(db_alias).create(
                    category=category,
                    locale=locale,
                    name=name,
                    description=description
                )
    
    # 2. MenuItem и MenuItemTranslation
    MenuItem = apps.get_model('core', 'MenuItem')
    MenuItemTranslation = apps.get_model('core', 'MenuItemTranslation')
    
    for menu_item in MenuItem.objects.using(db_alias).all():
        for locale in locales:
            # Проверяем, существует ли уже перевод
            if not MenuItemTranslation.objects.using(db_alias).filter(
                menu_item=menu_item, locale=locale
            ).exists():
                # Получаем первый существующий перевод для копирования или используем базовое значение
                existing_translation = menu_item.translations.first()
                if existing_translation:
                    name = existing_translation.name
                    description = existing_translation.description
                else:
                    # Используем базовое значение из модели
                    name = menu_item.name
                    description = menu_item.description
                
                # Создаем перевод
                MenuItemTranslation.objects.using(db_alias).create(
                    menu_item=menu_item,
                    locale=locale,
                    name=name,
                    description=description
                )
    
    # 3. Story и StoryTranslation
    Story = apps.get_model('core', 'Story')
    StoryTranslation = apps.get_model('core', 'StoryTranslation')
    
    for story in Story.objects.using(db_alias).all():
        for locale in locales:
            # Проверяем, существует ли уже перевод
            if not StoryTranslation.objects.using(db_alias).filter(
                story=story, locale=locale
            ).exists():
                # Получаем первый существующий перевод для копирования или используем базовое значение
                existing_translation = story.translations.first()
                if existing_translation:
                    title = existing_translation.title
                    slug = existing_translation.slug
                    excerpt = existing_translation.excerpt
                    content = existing_translation.content
                else:
                    # Используем базовое значение из модели
                    title = story.title
                    slug = story.slug
                    excerpt = story.excerpt
                    content = story.content
                
                # Создаем перевод
                StoryTranslation.objects.using(db_alias).create(
                    story=story,
                    locale=locale,
                    title=title,
                    slug=slug,
                    excerpt=excerpt,
                    content=content
                )
    
    # 4. ContentSection и ContentSectionTranslation
    ContentSection = apps.get_model('core', 'ContentSection')
    ContentSectionTranslation = apps.get_model('core', 'ContentSectionTranslation')
    
    for section in ContentSection.objects.using(db_alias).all():
        for locale in locales:
            # Проверяем, существует ли уже перевод
            if not ContentSectionTranslation.objects.using(db_alias).filter(
                section=section, locale=locale
            ).exists():
                # Получаем первый существующий перевод для копирования или используем базовое значение
                existing_translation = section.translations.first()
                if existing_translation:
                    title = existing_translation.title
                    subtitle = existing_translation.subtitle
                    description = existing_translation.description
                    content = existing_translation.content
                else:
                    # Используем базовое значение из модели (если есть)
                    title = getattr(section, 'title', f'Раздел #{section.id}')
                    subtitle = getattr(section, 'subtitle', '')
                    description = getattr(section, 'description', '')
                    content = getattr(section, 'content', '')
                
                # Создаем перевод
                ContentSectionTranslation.objects.using(db_alias).create(
                    section=section,
                    locale=locale,
                    title=title,
                    subtitle=subtitle,
                    description=description,
                    content=content
                )
    
    # 5. FooterSection и FooterSectionTranslation
    FooterSection = apps.get_model('core', 'FooterSection')
    FooterSectionTranslation = apps.get_model('core', 'FooterSectionTranslation')
    
    for section in FooterSection.objects.using(db_alias).all():
        for locale in locales:
            # Проверяем, существует ли уже перевод
            if not FooterSectionTranslation.objects.using(db_alias).filter(
                section=section, locale=locale
            ).exists():
                # Получаем первый существующий перевод для копирования или используем базовое значение
                existing_translation = section.translations.first()
                if existing_translation:
                    title = existing_translation.title
                    content = existing_translation.content
                else:
                    # Используем базовое значение из модели (если есть)
                    title = getattr(section, 'title', f'Секция #{section.id}')
                    content = getattr(section, 'content', '')
                
                # Создаем перевод
                FooterSectionTranslation.objects.using(db_alias).create(
                    section=section,
                    locale=locale,
                    title=title,
                    content=content
                )


def reverse_migration(apps, schema_editor):
    """Откат миграции - удаляем созданные переводы (опционально, можно оставить пустым)."""
    # Можно оставить пустым, так как это миграция данных
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_menuitemcategory_menuitemcategorytranslation_and_more'),
    ]

    operations = [
        migrations.RunPython(create_missing_translations, reverse_migration),
    ]
