# Generated by Django 5.0.1 on 2025-11-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_missing_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_pickup',
            field=models.BooleanField(default=False, verbose_name='Самовывоз'),
        ),
    ]
